name: "Toolbox tests"

on:
  workflow_call:

jobs:
  ui-e2e-tests:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:enterprise
        env:
          NEO4J_AUTH: neo4j/password
          NEO4JLABS_PLUGINS: '["apoc"]'
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        ports:
          - 7687:7687

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update system (Ubuntu)
        run: |
          # use apt-spy2 to select closest apt mirror,
          # which helps avoid connectivity issues in Azure;
          # see https://github.com/actions/virtual-environments/issues/675
          sudo gem install apt-spy2
          sudo apt-spy2 check
          sudo apt-spy2 fix --commit
          # need to run apt-get update after running apt-spy2 fix
          sudo apt-get -o Acquire::Retries=3 update
          # end of apt-spy2 workaround
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run @neo4j/graphql-toolbox unit tests
        run: yarn test:unit
        working-directory: packages/graphql-toolbox
      - name: Run @neo4j/graphql-toolbox e2e tests
        run: yarn test
        working-directory: packages/graphql-toolbox
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: password
          NEO_URL: bolt://localhost:7687
